## What is "Reshaping Arrays" in NumPy?

Reshaping means changing the shape of an array without changing its data. This is super useful when you're preparing data for machine learning models — especially for training, validation, reshaping inputs, and handling features and labels.

## Step 1: Import NumPy

In [1]:
import numpy as np

Always begin by importing NumPy.

## Step 2: Check Shape of an Array

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

(6,)


This is a 1D array with 6 elements.

## Step 3: Reshape to 2D Array

Suppose we want to reshape it into 2 rows and 3 columns.

In [6]:
a2 = a.reshape(2, 3)

In [7]:
print(a2)

[[1 2 3]
 [4 5 6]]


In [8]:
print(a2.shape)

(2, 3)


**Practical Note:** In ML, 2D arrays are common for features. For example, 2 samples (rows) with 3 features (columns) each.

## Step 4: Reshape to 3D Array

Let’s reshape into a 3D array — useful for sequences like time steps.

In [9]:
a3 = a.reshape(1, 2, 3)

In [10]:
print(a3)

[[[1 2 3]
  [4 5 6]]]


In [11]:
print(a3.shape)

(1, 2, 3)


**Practical Note:** This can represent 1 sample, 2 timesteps, and 3 features — common in RNNs or LSTM inputs.

## Step 5: Use -1 to Auto Infer Shape

You don’t always need to manually calculate dimensions.

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
a_reshaped = a.reshape(-1, 2)
print(a_reshaped)

[[1 2]
 [3 4]
 [5 6]]


* -1 tells NumPy: "You figure it out for me."
* Practical Use: -1 is extremely handy in ML pipelines when you're not sure of the dimension count.

## Step 6: Flattening the Array (ravel vs flatten)

Sometimes we want to convert any shape back to 1D.

In [13]:
print(a_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
b = a_reshaped.flatten()  # Returns a copy
print(b)

[1 2 3 4 5 6]


In [16]:
c = a_reshaped.ravel()    # Returns a view
print(c)

[1 2 3 4 5 6]


## Step 7: Reshape in ML Use Case (X, y)

In [17]:
# Suppose we have 6 samples, 1 feature each:
X = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 2D column vector (6 rows, 1 column)
X = X.reshape(-1, 1)
print(X)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Machine Learning models (like Scikit-learn) expect features in shape (n_samples, n_features)

## Step 8: Reshape Images for Deep Learning (e.g. CNNs)

Let’s say you have a grayscale image of size 28x28 pixels.

In [21]:
image = np.random.rand(28, 28)

# Reshape to include "batch size" and "channel"
image = image.reshape(1, 28, 28, 1)  # (batch_size, height, width, channels)
print(image.shape)


(1, 28, 28, 1)


Required shape format for many deep learning frameworks like TensorFlow/Keras.

## Recap – Common Reshape Use Cases

| Goal | Shape Example | Use Case |
| --- | --- | --- |
| Flatten array | (n,) | Feature extraction, ML models |
| 2D Features | (n_samples, n_features) | Scikit-learn |
| 3D Sequences | (samples, time_steps, features) | RNN/LSTM |
| 4D Images | (batch, height, width, channels) | CNNs |

## Reshape Before Training a Model

In [ ]:
from sklearn.linear_model import LinearRegression

X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Reshape X to (n_samples, n_features)
X = X.reshape(-1, 1)

model = LinearRegression()
model.fit(X, y)