## What You'll Learn:

* What is matrix transpose and why it's important
* What is the determinant of a matrix and its significance
* How to calculate both using NumPy
* Practical examples
* How these concepts are used in Machine Learning

## Prerequisite: Import NumPy

In [1]:
import numpy as np

## PART 1: Matrix Transpose

**What is Transpose?**

The transpose of a matrix flips it over its diagonal. That means:

* Rows become columns
* Columns become rows

Mathematically, if matrix A is:

$$ A= \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

Then, its transpose Aᵗ is:

$$ A^{T}= \begin{bmatrix}
1 & 3 \\
2 & 4
\end{bmatrix}
$$

**Code Example**

In [2]:
# Original matrix
A = np.array([[1, 2], [3, 4]])
print("Original Matrix A:\n", A)

Original Matrix A:
 [[1 2]
 [3 4]]


In [3]:
# Transpose
A_transposed = A.T
print("Transposed Matrix A^T:\n", A_transposed)

Transposed Matrix A^T:
 [[1 3]
 [2 4]]


## PART 2: Determinant of a Matrix

**What is a Determinant?**

The determinant is a **scalar** value that tells you about:

* Whether the matrix is **invertible** (non-zero determinant)
* The **volume scaling factor** of the transformation
* If rows/columns are **linearly independent**

For a 2x2 matrix:

$$A= \begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

Determinant is:

$$det(A)=ad-bc$$

**Code Example**

In [5]:
# Matrix
B = np.array([[4, 6], [3, 8]])
print("Matrix B:\n", B)

Matrix B:
 [[4 6]
 [3 8]]


In [6]:
# Determinant
det_B = np.linalg.det(B)
print("Determinant of B:", det_B)

Determinant of B: 14.000000000000004


## Practical Example in ML: Normal Equation

Let’s say you are solving Linear Regression using the Normal Equation:

$$ \theta=\left( X^{T}X \right)^{-1}X^{T}y $$

**Code Example:**

In [7]:
# Feature matrix X and target y
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3])

# Compute Transpose of X
X_T = X.T

# Compute X^T X
XTX = X_T @ X

# Check determinant before inverse
print("Determinant of X^T X:", np.linalg.det(XTX))

# Inverse of X^T X
XTX_inv = np.linalg.inv(XTX)

# Compute parameters theta
theta = XTX_inv @ X_T @ y
print("Parameters θ:", theta)

Determinant of X^T X: 6.0
Parameters θ: [-1.77635684e-15  1.00000000e+00]


This tells us that y = 1*x + 0, which perfectly fits our input data!

##  Summary Table

| Operation | NumPy Function | Use Case |
| --- | --- | --- |
| Transpose | A.T | Shape alignment, Linear Algebra |
| Determinant | np.linalg.det(A) | Inverse check, ML transformations |
| Inverse (extra) | np.linalg.inv(A) | Used in solving linear systems |