## Why Vectors and Matrices Matter in Machine Learning

* Vectors represent features, weights, biases, and gradients.
* Matrices represent data batches, weights in neural networks, etc.
* NumPy makes it easy to handle these structures efficiently.

## Step 1: Import NumPy

In [1]:
import numpy as np

**Note:** Always use np as an alias; it's the standard.

## Step 2: Creating Vectors

**1D Vector (Feature Vector)**

In [2]:
v = np.array([1, 2, 3])
print("Vector v:", v)

Vector v: [1 2 3]


**Practical Note:**

In ML, a feature vector for a single data point might look like this:

In [3]:
x = np.array([0.5, 0.8, 0.2])  # 3 features

## Step 3: Creating Matrices

**2D Matrix**

In [5]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Matrix M:\n", M)

Matrix M:
 [[1 2 3]
 [4 5 6]]


**Practical Note:**

A matrix can represent multiple samples:

In [6]:
X = np.array([[0.5, 0.8, 0.2], 
              [0.9, 0.3, 0.5]])  # 2 samples × 3 features

## Step 4: Shape, Size, Dimension

In [7]:
print("Shape of X:", X.shape)       # (2, 3)

Shape of X: (2, 3)


In [8]:
print("Size of X:", X.size)         # 6 elements

Size of X: 6


In [9]:
print("Dimension of X:", X.ndim)    # 2

Dimension of X: 2


## Step 5: Vector & Matrix Operations

**Addition**

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b =", a + b)

a + b = [5 7 9]


**Scalar Multiplication**

In [11]:
print("2 * a =", 2 * a)

2 * a = [2 4 6]


**Matrix Addition (Same Shape)**

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A + B:\n", A + B)

A + B:
 [[ 6  8]
 [10 12]]


## Step 6: Dot Product

**Vector Dot Product**

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)
print("Dot product:", dot)  # 1*4 + 2*5 + 3*6 = 32

Dot product: 32


**Matrix Multiplication**

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
print("Matrix product:\n", product)

Matrix product:
 [[19 22]
 [43 50]]


**Note:** Matrix multiplication is crucial in forward and backward passes in neural networks.

## Step 7: Transpose

In [15]:
X = np.array([[1, 2], [3, 4], [5, 6]])
print("X Transpose:\n", X.T)

X Transpose:
 [[1 3 5]
 [2 4 6]]


Transposing swaps rows and columns.

## Step 8: Reshape

In [16]:
a = np.array([1, 2, 3, 4, 5, 6])
reshaped = a.reshape((2, 3))
print("Reshaped array:\n", reshaped)

Reshaped array:
 [[1 2 3]
 [4 5 6]]


Used in ML when feeding data in batches (reshape features).

## Step 9: Broadcasting

In [17]:
a = np.array([[1], [2], [3]])  # Shape: (3,1)
b = np.array([10, 20, 30])     # Shape: (1,3)
result = a * b
print("Broadcasted result:\n", result)

Broadcasted result:
 [[10 20 30]
 [20 40 60]
 [30 60 90]]


Broadcasting makes element-wise operations work across shapes.

## Step 10: Identity & Zero Matrices

In [20]:
I = np.eye(3)
print("Identity:\n", I)

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
Z = np.zeros((2, 3))
print("Zeros:\n", Z)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


Use Case: Identity matrix is the "do nothing" matrix (like 1 for numbers).

## Step 11: Useful Matrix Functions

In [24]:
A = np.array([[1, 2], [3, 4]])

In [23]:
print("Sum:", np.sum(A))

Sum: 10


In [22]:
print("Max:", np.max(A))

Max: 4


In [25]:
print("Mean:", np.mean(A))

Mean: 2.5


In [26]:
print("Standard deviation:", np.std(A))

Standard deviation: 1.118033988749895


## Step 12: Inverse and Determinant

In [28]:
from numpy.linalg import inv, det

A = np.array([[1, 2], [3, 4]])

In [30]:
A_inv = inv(A)

print("Inverse:\n", A_inv)

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [32]:
A_det = det(A)

print("Determinant:", A_det)

Determinant: -2.0000000000000004


Not all matrices are invertible. You can check with det(A) != 0.

## Real ML Example: Linear Model

Given a dataset of X (features) and w (weights):

In [33]:
X = np.array([[1, 2], [3, 4], [5, 6]])   # 3 samples, 2 features
w = np.array([0.1, 0.2])                # weights
b = 0.5                                 # bias

# y = Xw + b
y = np.dot(X, w) + b
print("Predictions:", y)

Predictions: [1.  1.6 2.2]


This is how predictions work in Linear Regression, Perceptrons, etc.