## Prerequisites:

Install NumPy (if you haven’t already):

In [ ]:
pip install numpy

Now, import it:

In [1]:
import numpy as np

## 1. Matrix Creation

**Why it matters:**

In machine learning, matrices represent datasets, weights, features, etc.

**Example:**

In [2]:
A = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", A)

Matrix A:
 [[1 2]
 [3 4]]


In [3]:
B = np.array([[5, 6], [7, 8]])
print("Matrix B:\n", B)

Matrix B:
 [[5 6]
 [7 8]]


## 2. Matrix Shape and Size

**Why it matters:**

Understanding the shape is essential when performing operations like matrix multiplication or feeding data into models.

**Example:**

In [4]:
print("Shape of A:", A.shape)

Shape of A: (2, 2)


In [5]:
print("Size (total elements) of A:", A.size)

Size (total elements) of A: 4


## 3. Matrix Addition and Subtraction

**Why it matters:**

Used in gradient updates, error propagation, etc.

**Example:**

In [6]:
add = A + B
print("Addition:\n", add)

Addition:
 [[ 6  8]
 [10 12]]


In [7]:
sub = A - B
print("Subtraction:\n", sub)

Subtraction:
 [[-4 -4]
 [-4 -4]]


**Note:**
  
Dimensions must match for element-wise operations.

## 4. Scalar Multiplication

**Why it matters:**

Used to scale weights or normalize data.

**Example:**

In [9]:
scaled = 3 * A
print("Scalar Multiplication (3 * A):\n", scaled)

Scalar Multiplication (3 * A):
 [[ 3  6]
 [ 9 12]]


## 5. Element-wise Multiplication (Hadamard Product)

**Why it matters:**

Used in neural networks (element-wise ops in activation, etc.)

**Example:**

In [10]:
elementwise = A * B
print("Element-wise Multiplication:\n", elementwise)

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


## 6. Matrix Multiplication (Dot Product)

**Why it matters:**

Core of linear models (linear regression, neural nets, etc.)

**Example:**

In [11]:
dot = A @ B  # or np.dot(A, B)
print("Matrix Multiplication (A @ B):\n", dot)

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]


**Warning:**
  
Shapes must align: (m × n) @ (n × p) → (m × p)

## 7. Transpose of a Matrix

**Why it matters:**

Used to align matrices for dot products or gradient computations.

**Example:**

In [12]:
transpose_A = A.T
print("Transpose of A:\n", transpose_A)

Transpose of A:
 [[1 3]
 [2 4]]


## 8. Matrix Inverse

**Why it matters:**

Important in solving linear systems, finding weights in linear regression (normal equation).

**Example:**

In [13]:
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


**Note:**

Only square matrices with non-zero determinant can be inverted.

## 9. Matrix Determinant

**Why it matters:**

Used to check if matrix is invertible. In ML, sometimes in computing likelihoods (e.g. Gaussian distributions).

**Example:**

In [15]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


## 10. Identity Matrix

**Why it matters:**

Acts like 1 in matrix multiplication. Used to initialize weights or as regularization.

**Example:**

In [16]:
I = np.eye(2)
print("Identity Matrix:\n", I)

Identity Matrix:
 [[1. 0.]
 [0. 1.]]


## 11. Solving Linear Equations (Ax = b)

**Why it matters:**

Very useful in linear regression using normal equation.

$$ \theta=\left( X^{T}X \right)^{-1}X^{T}y $$

**Example:**

In [18]:
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])

x = np.linalg.solve(A, b)
print("Solution x:", x)

Solution x: [2.2 3.6]


## 12. Matrix Rank

**Why it matters:**

Used in checking data redundancy and feature independence.

**Example:**

In [19]:
rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)

Rank of A: 2


## 13. Eigenvalues and Eigenvectors

**Why it matters:**

Used in PCA (dimensionality reduction), understanding variance in datasets.

**Example:**

In [20]:
eig_vals, eig_vecs = np.linalg.eig(A)
print("Eigenvalues:\n", eig_vals)
print("Eigenvectors:\n", eig_vecs)

Eigenvalues:
 [1.38196601 3.61803399]
Eigenvectors:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


## 14. Stacking Matrices (row-wise and column-wise)

**Why it matters:**

Used when combining features or datasets.

**Example:**

In [21]:
row_stack = np.vstack((A, B))
col_stack = np.hstack((A, B))

print("Row-wise Stack:\n", row_stack)
print("Column-wise Stack:\n", col_stack)

Row-wise Stack:
 [[2 1]
 [1 3]
 [5 6]
 [7 8]]
Column-wise Stack:
 [[2 1 5 6]
 [1 3 7 8]]


## 15. Reshaping Matrices

**Why it matters:**

Used when feeding input to ML models (e.g. flattening image data).

**Example:**

In [24]:
C = np.array([[1, 5], [4, 7]])
reshaped = C.reshape(4, 1)
print("Reshaped C (4x1):\n", reshaped)

Reshaped C (4x1):
 [[1]
 [5]
 [4]
 [7]]


## 16. Broadcasting

**Why it matters:**

Simplifies operations between matrices of different shapes. Saves memory and speeds up computation.

**Example:**

In [25]:
D = np.array([[1], [2]])
E = np.array([[1, 5], [4, 7]])

broadcasted = D + E
print("Broadcasted Addition:\n", broadcasted)

Broadcasted Addition:
 [[2 6]
 [6 9]]


## Linear Regression Example Using Matrix Ops

In [26]:
# Features (X) and labels (y)
X = np.array([[1, 1], [1, 2], [1, 3]])  # Add 1 for bias term
y = np.array([1, 2, 3])

# θ = (XᵀX)^(-1) Xᵀy
theta = np.linalg.inv(X.T @ X) @ X.T @ y
print("Linear Regression Parameters (θ):", theta)

Linear Regression Parameters (θ): [-1.77635684e-15  1.00000000e+00]
