In [2]:
import numpy as np

In [3]:
# create array, matrix

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [6]:
# shape
print(a.shape, b.shape)

(4,) (2, 2)


In [8]:
# reshape

c = a.reshape((4, 1))
c

array([[1],
       [2],
       [3],
       [4]])

In [9]:
c.shape

(4, 1)

In [10]:
d = a.reshape((2, 2, 1))
d.shape

(2, 2, 1)

In [12]:
d = a.reshape((2, -1, 1))
d.shape

(2, 2, 1)

In [13]:
d = a.reshape((2, 2, -1))
d.shape

(2, 2, 1)

In [14]:
# concatenate

a = np.array([1, 2, 3])
b = np.array([4, 5])

c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5])

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
c

array([5, 7, 9])

In [16]:
c = a * b
c

array([ 4, 10, 18])

In [17]:
c = np.array([10])
d = a + c # broadcasting
d

array([11, 12, 13])

In [18]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [20]:
# slice
# list_name[start:end:step]
b = a[2:7]
b

array([3, 4, 5, 6, 7])

In [21]:
b = a[2:7:2]
b

array([3, 5, 7])

In [22]:
c = a[a>3]
c

array([4, 5, 6, 7, 8])

In [23]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
sum_a = np.sum(a)
sum_a

36

In [26]:
max_a = np.max(a)
max_a

8

In [27]:
min_a = np.min(a)
min_a

1

In [28]:
a = np.array([4, 2, 9, 6, 7, 3, 5])
b = np.sort(a)
b

array([2, 3, 4, 5, 6, 7, 9])

In [30]:
a = np.random.randint(0, 10, (3,4))
a

array([[7, 1, 2, 3],
       [5, 4, 2, 6],
       [2, 2, 1, 5]])

In [31]:
a = np.random.randint(-100, 100, (3,4))
a

array([[ 54, -20,  -1,  94],
       [-50, -18, -11,  49],
       [-74,  56,  64,  86]])

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.vstack(a, b)
c

TypeError: vstack() takes 1 positional argument but 2 were given

In [33]:
c = np.vstack((a, b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
c.shape

(2, 3)

In [35]:
c = np.hstack((a, b))
c

array([1, 2, 3, 4, 5, 6])

In [36]:
a

array([1, 2, 3])

In [38]:
# Normalize

mean_a = np.mean(a)
mean_a

2.0

In [39]:
std_a = np.std(a)
std_a

0.816496580927726

In [42]:
norm_a = (a - mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [43]:
np.mean(norm_a)

0.0

In [44]:
np.std(norm_a)

0.9999999999999999